
char mesage1[8000] = "____device ___________time ______date ___Voltage ___Current _____Power __Reactive\n";

char mesage2[800] = "<form action=\"/Reset\" method=\"POST\"><input type=\"submit\" value=\"Toggle LED\"></form>";

char menuHTML[800] = "<meta name=\"viewport\" content=\"width=300px\"/><style type=\"text/css\"> .boton{ font-size:15px; font-family:Verdana,Helvetica; font-weight:bold; width:160px; height:40px; border:2px solid black; border-radius: 5px; } </style><center><form action=\"/wifi\" method=\"POST\"><input type=\"submit\" value=\"WIFI\" class=\"boton\"></form><form action=\"/data\" method=\"POST\"><input type=\"submit\" value=\"DATA\" class=\"boton\"></form><form action=\"/calibrate\" method=\"POST\"><input type=\"submit\" value=\"CALIBRAR\" class=\"boton\"></form><form action=\"/setting\" method=\"POST\"><input type=\"submit\" value=\"SETTING\" class=\"boton\"></form></form><form action=\"/reset\" method=\"POST\"><input type=\"submit\" value=\"RESET\" class=\"boton\"></form></br></center>";

char wifiHTML[800] = "<meta name=\"viewport\" content=\"width=300px\"/><style type=\"text/css\"> .boton{ font-size:15px; font-family:Verdana,Helvetica; font-weight:bold; width:160px; height:40px; border:2px solid black; border-radius: 5px; } </style><center><form action=\"/login\" method=\"POST\"><input type=\"text\" name=\"ssid\" placeholder=\"SSID\" class=\"boton\"></br></br><input type=\"password\" name=\"password\" placeholder=\"Password\" class=\"boton\"></br></br><input type=\"submit\" value=\"Login\" class=\"boton\"></form></br></br><form action=\"/\" method=\"POST\"><input type=\"submit\" value=\"Inicio\" class=\"boton\"></form></center>";

char calibrateHTML[1500] = "<meta name=\"viewport\" content=\"width=300px\"/><style type=\"text/css\"> .boton{ font-size:15px; font-family:Verdana,Helvetica; font-weight:bold; width:160px; height:40px; border:2px solid black; border-radius: 5px; } </style><center><form action=\"/setcalibrate\" method=\"POST\"><input type=\"number\" step=\"any\" name=\"offset_Voltage\" placeholder=\"Offset Voltage\" class=\"boton\"></br><input type=\"submit\" value=\"Calibrar\" class=\"boton\"></form><form action=\"/setcalibrate\" method=\"POST\"><input type=\"number\" step=\"any\" name=\"offset_Current\" placeholder=\"Offset current\" class=\"boton\"></br><input type=\"submit\" value=\"Calibrar\" class=\"boton\"></form><form action=\"/setcalibrate\" method=\"POST\"><input type=\"number\" step=\"any\" name=\"gain_Voltage\" placeholder=\"Gain Voltage\" class=\"boton\"></br><input type=\"submit\" value=\"Calibrar\" class=\"boton\"></form><form action=\"/setcalibrate\" method=\"POST\"><input type=\"number\" step=\"any\" name=\"gain_Current\" placeholder=\"Gain Current\" class=\"boton\"></br><input type=\"submit\" value=\"Calibrar\" class=\"boton\"></form></br></br><form action=\"/\" method=\"POST\"><input type=\"submit\" value=\"Inicio\" class=\"boton\"></form></center>";

char settingHTML[2000]= "<meta name=\"viewport\" content=\"width=300px\"/><style type=\"text/css\"> .boton{ font-size:15px; font-family:Verdana,Helvetica; font-weight:bold; width:160px; height:40px; border:2px solid black; border-radius: 5px; } </style><center><form action=\"/setsetting\" method=\"POST\">Nombre del Dispositivo</br><input type=\"text\" size=\"10\" name=\"name_device\" placeholder=\"Nombre\" class=\"boton\"></br></br>Ganancia Tension</br><select name=\"PGAvoltage\" class=\"boton\"><option value=\"0\">1</option><option value=\"1\">2</option><option value=\"2\">4</option><option value=\"3\">8</option><option value=\"4\">16</option><option value=\"5\">32</option><option value=\"6\">64</option></select></br></br>Ganancia Intensidad</br><select name=\"PGAcurrent\" class=\"boton\"><option value=\"0\">1</option><option value=\"1\">2</option><option value=\"2\">4</option><option value=\"3\">8</option><option value=\"4\">16</option><option value=\"5\">32</option><option value=\"6\">64</option></select></br></br>Frecuencia Convertidores</br><select name=\"DataRate\" class=\"boton\"><option value=\"0\">30,000SPS</option><option value=\"1\">15,000SPS</option><option value=\"2\">7,500SPS</option><option value=\"3\">3,750SPS</option><option value=\"4\">2,000SPS</option><option value=\"5\">1,000SPS</option><option value=\"6\">500SPS</option><option value=\"7\">100SPS</option><option value=\"8\">60SPS</option><option value=\"9\">50SPS</option><option value=\"10\">30SPS</option><option value=\"11\">25SPS</option><option value=\"12\">15SPS</option><option value=\"13\">10SPS</option><option value=\"14\">5SPS</option><option value=\"15\">2.5SPS</option></select></br></br><input type=\"submit\" value=\"Guardar y Reset\" class=\"boton\"></form></br></br><form action=\"/\" method=\"POST\"><input type=\"submit\" value=\"Inicio\" class=\"boton\"></form></center>";

char styleHTML[800] = "<style type=\"text/css\"> .boton{ font-size:20px; font-family:Verdana,Helvetica; font-weight:bold; color:white; background:#638cb5; border:0px; border-radius: 5px; width:160px; height:40px; } .screanText{ font-size:20px; font-family:Verdana,Helvetica; font-weight:bold; color:white; background:#638cb5; border:0px; width:160px; height:40px; } </style>";

//<style type=\"text/css\"> .boton{ font-size:20px; font-family:Verdana,Helvetica; font-weight:bold; color:white; background:#638cb5; border:0px; width:160px; height:40px; } </style>
