
char mesage1[8000] = "____device ___________time ______date ___Voltage ___Current _____Power __Reactive\n";

char mesage2[800] = "<form action=\"/Reset\" method=\"POST\"><input type=\"submit\" value=\"Toggle LED\"></form>";

char menuHTML[800] = "<style type=\"text/css\"> .boton{ font-size:20px; font-family:Verdana,Helvetica; font-weight:bold; color:white; background:#638cb5; border:0px; width:160px; height:40px; } </style><form action=\"/wifi\" method=\"POST\"><input type=\"submit\" value=\"WIFI\" class=\"boton\"></form><form action=\"/data\" method=\"POST\"><input type=\"submit\" value=\"DATA\" class=\"boton\"></form><form action=\"/calibrate\" method=\"POST\"><input type=\"submit\" value=\"CALIBRAR\" class=\"boton\"></form></form><form action=\"/reset\" method=\"POST\"><input type=\"submit\" value=\"RESET\" class=\"boton\"></form></br>";

char wifiHTML[800] = "<style type=\"text/css\"> .boton{ font-size:20px; font-family:Verdana,Helvetica; font-weight:bold; color:white; background:#638cb5; border:0px; width:160px; height:40px; } </style><form action=\"/login\" method=\"POST\"><input type=\"text\" name=\"ssid\" placeholder=\"SSID\" class=\"boton\"></br><input type=\"password\" name=\"password\" placeholder=\"Password\" class=\"boton\"></br><input type=\"submit\" value=\"Login\" class=\"boton\"></form>";

char calibrateHTML[1000] = "<style type=\"text/css\"> .boton{ font-size:15px; font-family:Verdana,Helvetica; font-weight:bold; width:160px; height:40px; border:solid black; border-radius: 5px; } </style><form action=\"/setcalibrate\" method=\"POST\"><input type=\"number\" step=\"any\" name=\"offset_Voltage\" placeholder=\"Offset Voltage\" class=\"boton\">  <input type=\"submit\" value=\"Calibrar\" class=\"boton\"></br></br><input type=\"number\" step=\"any\" name=\"offset_Current\" placeholder=\"Offset current\" class=\"boton\">  <input type=\"submit\" value=\"Calibrar\" class=\"boton\"></br></br><input type=\"number\" step=\"any\" name=\"gain_Voltage\" placeholder=\"Gain Voltage\" class=\"boton\">  <input type=\"submit\" value=\"Calibrar\" class=\"boton\"></br></br><input type=\"number\" step=\"any\" name=\"gain_Current\" placeholder=\"Gain Current\" class=\"boton\">  <input type=\"submit\" value=\"Calibrar\" class=\"boton\"></br></form>";

char styleHTML[800] = "<style type=\"text/css\"> .boton{ font-size:20px; font-family:Verdana,Helvetica; font-weight:bold; color:white; background:#638cb5; border:0px; border-radius: 5px; width:160px; height:40px; } .screanText{ font-size:20px; font-family:Verdana,Helvetica; font-weight:bold; color:white; background:#638cb5; border:0px; width:160px; height:40px; } </style>";

//<style type=\"text/css\"> .boton{ font-size:20px; font-family:Verdana,Helvetica; font-weight:bold; color:white; background:#638cb5; border:0px; width:160px; height:40px; } </style>
